import test from 'node:test';
import assert from 'node:assert/strict';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {join} from 'node:path';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
const checkout=process.env.OMD_CHECKOUT;
const response=text=>({delta:{role:'assistant',content:text},finish_reason:'stop'});
test('packed plugin in real OMD: default off, native review, context, cancel, themes and disable', {timeout:240000,skip:!checkout?'Set OMD_CHECKOUT for the isolated real-host test':false},async t=>{
  const {frontendFixture,until}=await import(pathToFileURL(join(checkout,'test/fixtures/frontend.mjs')).href);
  const requests=[],main=[];let held=false,release;
  const packagePath=process.env.OMD_INTENT_PACKAGE||fileURLToPath(new URL('../omd-prompt-optimizer-0.1.0.tgz',import.meta.url));
  const f=await frontendFixture(t,{plugins:['file:'+packagePath],modelReply:async payload=>{
    const all=JSON.stringify(payload.messages);
    if(!all.includes('意图补全器')){if(payload.tools?.length)main.push(payload);return undefined;}
    requests.push(payload);
    const raw=payload.messages.filter(m=>m.role==='user').flatMap(m=>typeof m.content==='string'?[m.content]:m.content.filter(b=>b.type==='text').map(b=>b.text)).join('\n');
    const input=raw.split('【用户原话（逐字，供你引用；不要改写它）】\n')[1]?.split('\n\n【标识')[0];
    assert.ok(input,'original input is explicitly marked');
    const sessionId=raw.match(/sessionId=([^\s]+)/)?.[1],messageId=raw.match(/messageId=([^\s]+)/)?.[1];
    if(held)await new Promise(resolve=>{release=resolve;});
    if(input.includes('FILE_READ_CHECK')&&!payload.messages.some(m=>m.role==='tool'))return {delta:{role:'assistant',tool_calls:[{index:0,id:'read-intent-fixture',type:'function',function:{name:'read',arguments:JSON.stringify({path:'intent-check.txt'})}}]},finish_reason:'tool_calls'};
    return response(JSON.stringify({ops:[{op:'add_item',item:{id:'req-one',kind:'user_requirement',text:'保持功能，只调整本轮指定的外观。',quote:input,scope:'turn',sourceRefs:[{kind:'human',sessionId,messageId}]}}]}));
  }});
  t.after(()=>{release?.();});
  const {page}=f,editor=page.locator('[data-composer-input]');
  const artifacts=fileURLToPath(new URL('../test-artifacts/',import.meta.url));await mkdir(artifacts,{recursive:true});
  const panel=page.getByRole('dialog',{name:'需求理解',exact:true});
  const api=async(path,body)=>page.evaluate(async({path,body})=>{const r=await fetch('omd-intent/api'+path,{headers:{'Content-Type':'application/json','x-omd-intent':'1'},...(body===undefined?{}:{method:'POST',body:JSON.stringify(body)})});return {status:r.status,...await r.json()};},{path,body});
  const config=()=>api('/config');
  assert.equal((await config()).config.enabled,false);assert.equal((await config()).runtime.hooks,0);
  assert.equal(await page.getByRole('button',{name:'需求理解选项',exact:true}).count(),0);
  assert.equal(requests.length,0);
  const baseMain=main.at(-1);
  const settingsOpen=async()=>{await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('dialog',{name:'设置',exact:true}).getByRole('button',{name:'需求理解',exact:true}).click();};
  await settingsOpen();await page.getByRole('switch',{name:'启用需求理解',exact:true}).click();
  await until(async()=>(await config()).config.enabled);await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'需求理解选项',exact:true}).waitFor();
  const before=main.length;
  await editor.fill('只改颜色，保留 {{literal}} 和全部功能');await editor.press('Enter');
  await panel.getByRole('button',{name:'采用并发送',exact:true}).waitFor();
  assert.equal(requests.length,1);assert.equal(main.length,before);assert.equal(await editor.innerText(),'只改颜色，保留 {{literal}} 和全部功能');
  await panel.screenshot({path:join(artifacts,'review-light.png')});
  await panel.getByRole('button',{name:'编辑内容',exact:true}).click();
  await panel.getByLabel('随行内容',{exact:true}).fill('OMD_INTENT_PROBE：只改颜色，模板 {{literal}} 原样保留。');
  await panel.getByRole('button',{name:'采用并发送',exact:true}).click();
  await until(()=>main.length>before);
  assert.match(JSON.stringify(main.at(-1).messages).includes('OMD_INTENT_PROBE')?'OMD_INTENT_PROBE':'missing',/OMD_INTENT_PROBE/);
  assert.match(JSON.stringify(main.at(-1).messages),/\{\{literal\}\}/);
  assert.deepEqual(main.at(-1).tools,baseMain.tools,'plugin never changes the work model tool list');
  await until(async()=>await editor.innerText()==='');
  // Actual read-only tool round and automatic delivery use the configured provider.
  await writeFile(join(f.workspace,'intent-check.txt'),'READ_ONLY_FIXTURE_CONTENT');
  await panel.getByRole('button',{name:'关闭需求理解面板',exact:true}).click();await settingsOpen();
  await page.locator('.opi-settings').getByText('模型与上下文',{exact:true}).click();
  await page.getByRole('switch',{name:'读取项目文件',exact:true}).click();await until(async()=>(await config()).config.readTools);
  await page.getByLabel('优化权限',{exact:true}).selectOption('auto');await until(async()=>(await config()).config.permission==='auto');await page.keyboard.press('Escape');
  const readStart=requests.length,workStart=main.length;await editor.fill('FILE_READ_CHECK：读取测试文件，保留其他功能');await editor.press('Enter');
  await until(()=>main.length>workStart);assert.equal(requests.length-readStart,2);assert.match(JSON.stringify(requests.at(-1).messages),/READ_ONLY_FIXTURE_CONTENT/);
  await until(async()=>await editor.innerText()==='');
  for(const mode of ['light','dark']){
    if(await panel.isVisible())await panel.getByRole('button',{name:'关闭需求理解面板',exact:true}).click();
    await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('dialog',{name:'设置',exact:true}).getByRole('button',{name:'外观',exact:true}).click();
    await page.getByLabel('主题',{exact:true}).selectOption('codex-desktop');await page.getByLabel('明暗模式',{exact:true}).selectOption(mode);await until(async()=>await page.locator('html').getAttribute('data-appearance')===mode);await page.keyboard.press('Escape');
    await page.getByRole('button',{name:'需求理解选项',exact:true}).click();
    const advanced=panel.getByRole('button',{name:'档位、模型与上下文',exact:false});if(await advanced.getAttribute('aria-expanded')!=='true')await advanced.click();
    await panel.screenshot({path:join(artifacts,'options-'+mode+'.png')});
    await page.setViewportSize({width:390,height:844});
    await until(async()=>{const b=await panel.boundingBox();return b&&b.x>=0&&b.y>=0&&b.x+b.width<=390;});
    await page.screenshot({path:join(artifacts,'mobile-'+mode+'.png')});
    await page.setViewportSize({width:1440,height:1000});
  }
  await panel.getByRole('button',{name:'关闭需求理解面板',exact:true}).click();
  // Stop in flight and then turn the component off: no stale result may dispatch.
  held=true;await editor.fill('取消这一轮的解释');await editor.press('Enter');await until(()=>!!release);
  const beforeCancel=main.length;await panel.getByRole('button',{name:'停止',exact:true}).click();release();release=null;held=false;
  await until(async()=>(await config()).runtime.requests===0);assert.equal(main.length,beforeCancel);assert.equal(await editor.innerText(),'取消这一轮的解释');
  if(await panel.isVisible())await panel.getByRole('button',{name:'关闭需求理解面板',exact:true}).click();
  held=true;await editor.fill('关闭时必须取消，不允许自动发送');await editor.press('Enter');await until(()=>!!release);
  if(await panel.isVisible())await panel.getByRole('button',{name:'关闭需求理解面板',exact:true}).click();
  await settingsOpen();await page.getByRole('switch',{name:'启用需求理解',exact:true}).click();release();release=null;held=false;
  await until(async()=>(await config()).runtime.hooks===0);await page.keyboard.press('Escape');
  await until(async()=>await page.getByRole('button',{name:'需求理解选项',exact:true}).count()===0);
  assert.equal(await page.locator('style[data-plugin="omd-intent-assistant"]').count(),0);
  const calls=requests.length;await editor.fill('关闭后原样发送');await editor.press('Enter');await until(()=>main.length>beforeCancel);
  assert.equal(requests.length,calls);assert.deepEqual(main.at(-1).tools,baseMain.tools);
  const latestUser=main.at(-1).messages.filter(m=>m.role==='user').at(-1);assert.match(JSON.stringify(latestUser),/关闭后原样发送/);
  assert.equal((await config()).runtime.staged,0);
  await page.reload();await editor.waitFor();assert.equal((await config()).config.enabled,false);assert.equal(await page.getByRole('button',{name:'需求理解选项',exact:true}).count(),0);
  await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('dialog',{name:'设置',exact:true}).getByRole('button',{name:'推荐插件',exact:true}).click();
  const card=page.locator('.tx-recommended-card').filter({has:page.getByRole('heading',{name:'需求理解 · OMD UI 增强版',exact:true})});
  await until(()=>card.getByRole('button',{name:'卸载',exact:true}).isEnabled());await card.getByRole('button',{name:'卸载',exact:true}).click();
  await until(async()=>{const state=await(await page.request.get(new URL('trisoul-x/recommended-plugins',page.url()).href)).json();const plugin=state.plugins.find(p=>p.id==='omd-intent-assistant');if(plugin?.error)throw Error(plugin.error);return !state.busy&&!plugin.installed;},60000);
  assert.equal((await page.request.get(new URL('omd-intent/api/config',page.url()).href)).status(),404,'uninstall removes the API');
  assert.deepEqual(f.errors,[]);
  console.log('Real-host evidence:',JSON.stringify({interpreterCalls:requests.length,workCalls:main.length,toolsUnchanged:true,defaultDisabled:true,disabledHooks:0,lightDark:true,mobile:true,readOnlyTool:true,automaticDelivery:true,uninstalled:true,artifacts}));
});
